[package]
name = "toowav"
version = "0.1.0"
edition = "2021"

[dependencies]
symphonia = { version = "0.5", features = ["all"] }
rubato = "0.12"
hound = "3.5"
clap = { version = "4.4", features = ["derive"] }
